### ISSUE TITLE
Windows10 + Python3.7 issue

### ISSUE THREAD

**Issue by brian7nt** [anntzer/redeal#14]
From within the directory that includes redeal.py, I get:

File "redeal.py", line 23, in <module>
    from . import global_defs, dds, util
ImportError: cannot import name 'global_defs' from '__main__' (redeal.py)

when I type >python redeal.py

Redeal was installed via the >python -mpip.... command in the documentation. TIA.

**Comment by anntzer** [comment]
Don't run redeal.py.  Run redeal.  Likely not from the directory that contains redeal.py, in fact.

**Comment by brian7nt** [comment]
I'm sorry, but I don't understand what that means--from within the command module I get:

C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal>python redeal.py
Traceback (most recent call last):
  File "redeal.py", line 23, in <module>
    from . import global_defs, dds, util
ImportError: cannot import name 'global_defs' from '__main__' (redeal.py)

OR

C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal>python redeal
(null): can't open file 'redeal': [Errno 2] No such file or directory

C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal>redeal
'redeal' is not recognized as an internal or external command,
operable program or batch file.

From within a python (IDLE) window, I get:
RESTART: C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal\redeal.py 
Traceback (most recent call last):
  File "C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal\redeal.py", line 23, in <module>
    from . import global_defs, dds, util
ImportError: cannot import name 'global_defs' from '__main__' (C:\Users\bjr1\Downloads\redeal-master\redeal-master\redeal\redeal.py)

when I F5 the module...

p.s. I had this working on an older laptop/windows/python config:(

**Comment by anntzer** [comment]
Can you provide the entire install log (from pip install etc.)?

**Comment by brian7nt** [comment]
I deleted the redeal directory structure, so all I had was the .zip file; from the command prompt:

C:\Users\bjr1\Downloads>python -mpip install redeal-master.zip
Processing c:\users\bjr1\downloads\redeal-master.zip
Requirement already satisfied: colorama>=0.2.4 in c:\users\bjr1\appdata\local\programs\python\python37-32\lib\site-packages (from redeal==0.2.0) (0.3.9)
Installing collected packages: redeal
  Found existing installation: redeal 0.2.0
    Uninstalling redeal-0.2.0:
      Successfully uninstalled redeal-0.2.0
  Running setup.py install for redeal ... done
Successfully installed redeal-0.2.0

Your assistance is much appreciated!

**Comment by brian7nt** [comment]
success; it took me "awhile" to figure out the result of the python -mpip... command was an executable...then I had to find it...and update path variable. My questions must have been very confusing. Sorry about that...

**Comment by anntzer** [comment]
Good to hear it works for you, alwyas happy to help.
