### ISSUE TITLE
redeal: command not found (Ubuntu 18)

### ISSUE THREAD

**Issue by bri-n** [anntzer/redeal#17]
I entered the following command in a terminal:
python -m pip install --user --upgrade git+https://github.com/anntzer/redeal
The last 3 lines output were:
Installing collected packages: colorama, enum34, redeal
  Running setup.py install for redeal ... done
Successfully installed colorama-0.4.1 enum34-1.1.6 redeal-0.2.0

So everything looks ok...   But when I enter    "redeal -n2"  I get "redeal: command not found"
Any thoughts on what I should look at to resolve this?

I am running Ubuntu 18.10.  Python version is 2.7.15+

**Comment by bri-n** [comment]
Thanks. That looks like it is going to work.  I am getting an error re Tkinter missing, but I can deal with that.
That was a super quick response!   :-)

**Comment by anntzer** [comment]
You are welcome :)
