### ISSUE TITLE
about opening_lead.py in example

### ISSUE THREAD

**Issue by spade14** [anntzer/redeal#18]
Hi
I think the library is very helpful,thanks a lot.But I would like to confirm about the OpeningLeadSim

Actually I modified the part OpeningLeadSim(Simulation), adding `print(self.payoff.table)`  in the final() part,  and run `redeal opening_lead.py -n10` to see the IMP difference between leads.
 I wonder the data in self.payoff.table is the IMP difference between different leads,If Yes,I think the distribution of the IMP difference is kind of weird. there are many 2 and -2 in it, with no +1 -1(usually caused by an overtrick)  or +10 -10( the 3NT made or went down).

Would you check if for me? Thank you

**Comment by anntzer** [comment]
Oops, I got the sign wrong in OpeningLeadSim... I was scoring tricks for the defense, which was always down a bunch and thus scored n*50 (hence the 2 imps difference).  That's very embarrassing, and fixed now as of master.  Can you have a look?

**Comment by spade14** [comment]
I have checked that,the distribution became normal.Thank you.
Noticing SQ had a all plus column (I believe that is the best lead?),I think now the result matrix is transposed, which means the column is your lead choice and row is the lead you compare with.
