### ISSUE TITLE
which unix env is supported, can u state your env?

### ISSUE THREAD

**Issue by larrycai** [anntzer/redeal#19]
I tried to install it in ubuntu bionic + python 3.7 env, but it doesn't work, it ends it could be an issue in upstream which I register there https://github.com/dds-bridge/dds/issues/94 

I wonder which platform do you use, will be nice if u have workable Unix platform. If u only verified in windows, then I will focus on windows

BTW: found this from your blog http://datadaydreams.com/posts/a-simulation-tutorial-for-better-decisionmaking-at-bridge/ (excellent work!!)

**Comment by anntzer** [comment]
Things work on Linux for me (Arch Linux or Fedora).  In fact the CI testing (via azure-pipelines.yml) is only done on Linux...
The memory issue you mention on the dds tracker should have been fixed by https://github.com/anntzer/redeal/commit/d7e38aeb0a5d91333a561b1db9455612337faa6d.

**Comment by larrycai** [comment]
I tried for that pull (change the link in submodule), it doesn't work on ubuntu, i tried it for fedora/centos as well.

Can you state the env for fedora or arch linux? so I can try for docker like archlinux/base

**Comment by larrycai** [comment]
from the `azure-pipelines.yml` looks it supports `ubuntu 16.04`

I tried below `fedora` according to the guideline with no success, will be appreciated if u can make it work

````
$ docker run -it  fedora:31
# dnf install -y git gcc-c++ make boost-devel python3-pip
# python3 -mpip install --user --upgrade git+https://github.com/anntzer/redeal
# cd /root/.local/lib/python3.7/site-packages/redeal
# export LD_LIBRARY_PATH=$PWD
# python3 -c 'from ctypes import *; dll = CDLL("libdds.so");'
sh: free: command not found
Memory::GetPtr: 0 vs. 0
Memory::GetPtr: 0 vs. 0
````

**Comment by larrycai** [comment]
Same for `ubuntu 18.04 (bionic)`, not sure which is missed

````
$ docker run -it ubuntu:bionic
apt-get update
apt-get install -y g++ make git libboost-all-dev libomp-dev python3 python3-pip
python3 -mpip install --user --upgrade git+https://github.com/anntzer/redeal
cd /root/.local/lib/python3.6/site-packages/redeal
export LD_LIBRARY_PATH=$PWD
python3 -c 'from ctypes import *; dll = CDLL("libdds.so");'
Memory::GetPtr: 0 vs. 0
Memory::GetPtr: 0 vs. 0
````

**Comment by anntzer** [comment]
You need to install procps-ng (on arch/fedora -- whatever provides /usr/bin/free on other distros).  I guess that can be considered a dependency of dds... feel free to open an issue on their tracker.

**Comment by larrycai** [comment]
I installed the `procps` for `ubuntu` & `procps-ng`  for fedora. but both don't work still.

**Comment by anntzer** [comment]
What does running `/usr/bin/free -k` return?

**Comment by larrycai** [comment]
````
# free -k
              total        used        free      shared  buff/cache   available
Mem:        1989472      601400      169936      107636     1218136      681832
Swap:             0           0           0
````

has issue with swap ?

**Comment by anntzer** [comment]
I pushed a (local) patch to dds which should fix that.

**Comment by larrycai** [comment]
excellent, now it works in simple way, see `Dockerfile`

````
FROM python:3.7.5-slim-buster
RUN apt-get update && apt-get install -y g++ make git libboost-all-dev procps
RUN python -mpip install --upgrade git+https://github.com/anntzer/redeal
````

then I can simple do

````
$ docker build -t anntzer/redeal .
$ docker run anntzer/redeal redeal
♠Q87♡T9♢J5♣KT9843 ♠JT5♡K5♢Q9732♣J72 ♠A64♡AQ876♢AK84♣5 ♠K932♡J432♢T6♣AQ6
♠A5♡Q754♢K4♣KJ954 ♠QJ74♡9♢652♣T7632 ♠K986♡AT32♢QT98♣Q ♠T32♡KJ86♢AJ73♣A8
♠KJ♡QJ984♢AKT8♣62 ♠854♡AK32♢62♣JT75 ♠AQT963♡65♢753♣Q4 ♠72♡T7♢QJ94♣AK983
♠A4♡QT3♢A97♣AQ864 ♠JT32♡J7♢KQ84♣T92 ♠865♡AK96♢T632♣K7 ♠KQ97♡8542♢J5♣J53
♠T3♡KJ3♢A542♣KJ75 ♠A2♡Q962♢K876♣QT9 ♠874♡A74♢QT♣86432 ♠KQJ965♡T85♢J93♣A
♠K92♡AKT872♢5♣AJ5 ♠8743♡9♢J98643♣T8 ♠AJT6♡QJ65♢QT2♣KQ ♠Q5♡43♢AK7♣976432
♠J♡A743♢T8643♣K63 ♠AK742♡KT95♢J2♣J4 ♠Q953♡86♢A97♣QT87 ♠T86♡QJ2♢KQ5♣A952
♠J8♡2♢KJ84♣KJT652 ♠432♡QJ874♢T7♣973 ♠KQT♡653♢A652♣Q84 ♠A9765♡AKT9♢Q93♣A
♠KT72♡QJT82♢9♣Q63 ♠J643♡943♢K852♣74 ♠A♡AK65♢AT743♣K85 ♠Q985♡7♢QJ6♣AJT92
♠AKJ84♡KT5♢AT3♣QT ♠96♡A982♢J972♣J76 ♠QT3♡Q♢Q84♣A98432 ♠752♡J7643♢K65♣K5

Tries: 10
````

Do you want me to contribute PR in your document? or leaving this in issue is enough

**Comment by larrycai** [comment]
create repo for the docker image https://github.com/larrycai/docker-redeal, I will use this to reproduce your article.

**Comment by anntzer** [comment]
In theory nearly any unix env should work now (I patched out the dependency on procps-ng), so I don't think there's much to add and this can be closed now?

**Comment by larrycai** [comment]
thx
