### ISSUE TITLE
local variable referenced before assignment

### ISSUE THREAD

**Issue by EricSiegNW** [anntzer/redeal#20]
Likely an issue on my part, but I'm having trouble defining variables to the increment during do and then reference during final.

All the approaches I've taken result in a "local variable 'handsFound' referenced before assignment" error in the do block.

Thoughts on correct syntax/way to do this?

Example:

def initial():
	global handsFound
	handsFound = 0

// skipping accept block

def do(deal):
	handsFound += 1

This throws an error saying that local variable handsFound referenced before assignment.

I've tried moving handsFound out of initial and into the initial lines, I've tried nonlocal, other ways of assigning, assigning directly, etc.

Curious what approach I should be taking to make this work as it seems like a core use case.

Thanks!

**Comment by anntzer** [comment]
You need to declare handsFound as global in do(); see e.g. https://docs.python.org/3/faq/programming.html#why-am-i-getting-an-unboundlocalerror-when-the-variable-has-a-value.

**Comment by anntzer** [comment]
I'll assume you got this fixed, but feel free to reopen if you need more info.
