### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pngmafia** [anntzer/redeal#21]
Collecting git+https://github.com/anntzer/redeal
  Cloning https://github.com/anntzer/redeal to /tmp/pip-N1WQNh-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-N1WQNh-build/setup.py", line 31
        raise Exception(f"Invalid patch: {old}")
                                              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-N1WQNh-build/

**Comment by anntzer** [comment]
You nedd python>=3.6.  I realize the warning could be clearer though, will change that.

**Comment by anntzer** [comment]
Should be fixed now, closing but feel free to reopen if you need more info.
