### ISSUE TITLE
--seed Seed does not work?

### ISSUE THREAD

**Issue by boput** [anntzer/redeal#22]
At least on my installation on Windows 10/Python 3.8 and Debian (buster), seeding with the same seed does not produce same deals.
Windows:
C:\Root\bridge\redeal>redeal --seed 1 -n1
♠T♥964♦T63♣QJT752 ♠K42♥AT52♦AKJ7♣K8 ♠J763♥QJ73♦Q5♣A63 ♠AQ985♥K8♦9842♣94
Tries: 1
C:\Root\bridge\redeal>redeal --seed 1 -n1
♠J2♥A85♦QT97♣QJ86 ♠K♥J7432♦KJ83♣AT5 ♠964♥QT6♦A42♣K742 ♠AQT8753♥K9♦65♣93
Tries: 1

Debian:
boput@Perun:~/bridge/redeal$ redeal --seed 1 -n1
♠762♥AK52♦J♣J9764 ♠KT53♥J♦KT7532♣T8 ♠Q984♥T8♦964♣AK52 ♠AJ♥Q97643♦AQ8♣Q3
Tries: 1
Segmentation fault (core dumped)
boput@Perun:~/bridge/redeal$ redeal --seed 1 -n1
♠QJT98♥KQJ♦83♣Q62 ♠♥AT3♦KJ952♣AK975 ♠K7654♥986♦74♣JT8 ♠A32♥7542♦AQT6♣43
Tries: 1

Sometimes is useful to get same deals for some simulations.  Thanks for your (re)deal in python skin.

**Comment by anntzer** [comment]
Ah, good catch.  Should be fixed now, can you try it?

**Comment by boput** [comment]
You are quick!

It works now. Thanks.

**Comment by boput** [comment]
It works now. Thank you.
