### ISSUE TITLE
pip install redeal fails under 3.10

### ISSUE THREAD

**Issue by tomc** [anntzer/redeal#25]
I suspect it has to do with the requirements line over version >=3.6 rather than >='3.6'.   3.10 is read in as 3.1 and then compared with 3.6 and fails.

**Comment by anntzer** [comment]
What did you try and what error did you get?  Things seem to work fine on Py3.10, locally.

**Comment by tomc** [comment]
$ pip install redeal

ERROR: Could not find a version that satisfies the requirement redeal (from versions: none)
ERROR: No matching distribution found for redeal

----------------------

I'm sure the _software_ works fine, it's the installation process that isn't working because it misdetects 3.10 as 3.1 and doesn't match >=3.6

I recall reading about numerous packages which had this problem when 3.10 was new.  I'm not familiar enough with the specifics of making a PyPI package to suggest an exact solution.

**Comment by anntzer** [comment]
That's just because the package is not on PyPI at all, your command fail regardless of Python version.  See https://github.com/anntzer/redeal#installation for installation instructions.

**Comment by tomc** [comment]
Apologies.  It's been a while since I installed under 3.8 - I recently was porting everything to 3.10 and ran into this issue.  I had forgotten this had separate installation instructions.
