### ISSUE TITLE
How do I get the Gui to run?

### ISSUE THREAD

**Issue by BROnstott** [anntzer/redeal#26]
When I run C:\Users\Bert\AppData\Roaming\Python\Python37\Scripts redeal-gui from the command line, nothing happens.  

redeal-gui.exe is present in the folder:
 Directory of C:\Users\Bert\AppData\Roaming\Python\Python37\Scripts

01/30/2022  04:22 PM    <DIR>          .
01/30/2022  04:22 PM    <DIR>          ..
10/09/2019  08:42 PM           102,791 epylint.exe
07/02/2020  03:03 PM           102,803 iptest.exe
07/02/2020  03:03 PM           102,803 iptest3.exe
07/02/2020  03:03 PM           102,796 ipython.exe
07/02/2020  03:03 PM           102,796 ipython3.exe
10/09/2019  08:42 PM           102,781 isort.exe
07/02/2020  03:03 PM           102,795 jupyter-kernel.exe
07/02/2020  03:03 PM           102,833 jupyter-kernelspec.exe
07/02/2020  03:03 PM           102,791 jupyter-migrate.exe
07/02/2020  03:03 PM           102,812 jupyter-run.exe
07/02/2020  03:03 PM           102,796 jupyter-troubleshoot.exe
07/02/2020  03:03 PM           102,791 jupyter.exe
07/02/2020  03:03 PM           102,787 pygmentize.exe
10/09/2019  08:42 PM           102,789 pylint.exe
10/09/2019  08:42 PM           102,795 pyreverse.exe
07/02/2020  03:02 PM            24,878 pywin32_postinstall.py
07/02/2020  03:02 PM             3,010 pywin32_testall.py
01/30/2022  04:22 PM               437 redeal-gui-script.pyw
01/30/2022  04:22 PM            75,264 redeal-gui.exe
01/30/2022  04:22 PM               436 redeal-script.py
01/30/2022  04:22 PM            74,752 redeal.exe
10/09/2019  08:42 PM           102,791 symilar.exe

I can type redeal and it generates the expected output:
C:\Users\Bert\AppData\Roaming\Python\Python37\Scripts>redeal
♠T43♡A743♢AQ♣AK83 ♠AQ2♡KQ♢8743♣QT95 ♠98765♡52♢KJT65♣7 ♠KJ♡JT986♢92♣J642
♠AK♡9642♢853♣K643 ♠T6532♡KQ♢KJT4♣Q8 ♠Q9874♡J8♢2♣AT752 ♠J♡AT753♢AQ976♣J9
♠T987♡T♢AT62♣QJ93 ♠Q4♡AKQ9♢QJ84♣754 ♠KJ63♡J7♢753♣AT82 ♠A52♡865432♢K9♣K6
♠4♡J986♢T9853♣K63 ♠J62♡T54♢K642♣982 ♠KQ83♡AK7♢QJ7♣AJ4 ♠AT975♡Q32♢A♣QT75
♠KT75♡AQ9♢A86♣A54 ♠Q9♡J754♢J542♣J98 ♠A643♡T832♢T3♣732 ♠J82♡K6♢KQ97♣KQT6
♠2♡AQ♢AK987♣K9643 ♠AK9764♡943♢T6♣JT ♠83♡JT765♢QJ4♣AQ7 ♠QJT5♡K82♢532♣852
♠74♡T965♢T9753♣JT ♠9532♡AJ♢KQ8♣8765 ♠KJT♡K42♢642♣AQ42 ♠AQ86♡Q873♢AJ♣K93
♠A83♡T2♢AQT3♣AQJ6 ♠742♡Q74♢J6♣K9843 ♠QJT♡KJ98♢K54♣752 ♠K965♡A653♢9872♣T
♠KJ85♡96♢AKT♣A932 ♠AT7643♡J842♢8♣K5 ♠92♡AT5♢972♣QJT74 ♠Q♡KQ73♢QJ6543♣86
♠A♡Q952♢T7632♣A95 ♠QJ75♡KJT76♢98♣KT ♠KT9♡84♢A54♣Q7632 ♠86432♡A3♢KQJ♣J84

Tries: 10

What am I doing wrong? I'm not a Windows developer and have only a very rudimentary knowledge of python. (My programming experience was as an engineer, and started with Fortran and ended with Visual Basic and web development.).

**Comment by anntzer** [comment]
Perhaps try `redeal --gui`.  Also, does `python -mtkinter` do anything?  If the latter displays nothing, then there's a problem with your python install :(

**Comment by BROnstott** [comment]
Antony  –  python -mtkinter pops up a small window. So I guess that means python is ok. And redeal –gui brings up the gui.  Thanks.

 

 

 

 

 

Bert Onstott

3303 N Sutton Sq

Stafford, TX 77477

 ***@***.***> ***@***.***

713-851-1511

**Comment by anntzer** [comment]
Let's stick to `redeal --gui`, then.
