### ISSUE TITLE
Can't install, macOs

### ISSUE THREAD

**Issue by EmanuelU** [anntzer/redeal#30]
It seems making the c++ lib doesn't work anymore, because of a bunch of deprecation messages in par.cpp

`      __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
              #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                            ^
      16 errors generated.
      make: *** [Par.o] Error 1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>`

**Comment by anntzer** [comment]
Good catch, should be fixed now.
