### ISSUE TITLE
deprecation for pip 

### ISSUE THREAD

**Issue by EmanuelU** [anntzer/redeal#31]
is this something on my end? 

trying to install this in a venv

 DEPRECATION: redeal is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by anntzer** [comment]
Nothing to do here, the build details will change in a future version of pip but this shouldn't really affect the end result.
