### ISSUE TITLE
Possible to `pip install` without dev env in jupyter notebook?

### ISSUE THREAD

**Issue by larrycai** [anntzer/redeal#36]
In current `setup.py`, it needs to download dds dependance and build it on unix platform, it makes very tricky to install inside jupyter notebook.

Recently I am studying the AI bridge engine project, https://github.com/lorserker/ben which I want to do some testing with `redeal`, but installation is so painful.

In that project, I checked some env https://github.com/lorserker/ben/issues/13#issuecomment-1794861503, in ubuntu `libdds.so` already exists.

So is it possible to release in pypi?

* a light weight version which user can prepare dds in advance without recompiling
* store some popular libraries somewhere like Windows without recompiling

**Comment by anntzer** [comment]
Not everyone is using ubuntu.
On the other hand upstream is providing libdds.so too (the third link at http://privat.bahnhof.se/wb758135/bridge/dll.html).  Does it work for you if you use that directly?

**Comment by larrycai** [comment]
Good, so do we have doc to install `libdds.so` in advance and make `pip install --user --upgrade git+https://github.com/anntzer/redeal`

Then in jupyter notebook, I can

````
$ curl -o $HOME/libdds.so <some url>
# export LD_LIBRARY_PATH=$HOME/libdds.so:$LD_LIBRARY_PATH # ??
$ pip install --user --upgrade git+https://github.com/anntzer/redeal
````

Just try to avoid to install `make` in my env ;-)

**Comment by larrycai** [comment]
Ok, I hacked to make it work (hopefully it can be better)

## Prepare the libdds.so 

If it is ubuntu env, then default is ok

```
$ apt-get install -y libdds-dev # mostly it install libdds & libboost-thread
$ dpkg -L libdds-dev  # locate the libdds.so
/usr/lib/x86_64-linux-gnu/libdds.so
```

## Patch redeal and install

```
$ git clone https://github.com/anntzer/redeal
$ cd redeal
$ vi setup.pl # comments below two lines to avoid building libdds
#    cmdclass={"build_ext": build_ext},
#    ext_modules=[setuptools.Extension("", [])],
$ pip install .  # install redeal without handling libdds.so
```

## Hack the libdds.so to redeal

when u run the redeal for some commands, it will complain about the `libdds.so`, see code https://github.com/anntzer/redeal/blob/main/redeal/dds.py#L168  as well

```
  File "/opt/conda/lib/python3.11/site-packages/redeal/dds.py", line 117, in solve
    _check_dll("solve")
  File "/opt/conda/lib/python3.11/site-packages/redeal/dds.py", line 185, in _check_dll
    raise Exception(f"Unable to load DDS; {name} is not available")
```

surely, you can use `pip show redeal` can locate the folder as well.

Then u know where to put the `libdds.so` file

````
$ cp /usr/lib/x86_64-linux-gnu/libdds.so /opt/conda/lib/python3.11/site-packages/redeal/dds.py
````

Finally it works without development env for compiling `libdds.so`

## Tips: where to find libdds

* You can always check https://privat.bahnhof.se/wb758135/bridge/dll.html to see whether existing pre-built libraries works
* use system `libdds` package, like ubuntu
* if not, u can pre-compile the `libdds` in the place you can download in advance

**Comment by larrycai** [comment]
as it works for me, i close the ticket. Thank for quick response.
