### ISSUE TITLE
Hand.losers is currently implemented in a non-standard way

### ISSUE THREAD

**Issue by palamau** [anntzer/redeal#38]
The current implementation of loser evaluates a holding of Qxx as 2.5 loser.  Based on https://en.wikipedia.org/wiki/Losing-Trick_Count it would appear that this holding should evaluate to 2 losers.

There are alternative ways of evaluating the number of losers but I think we should implement using the "standard" definition of losers.  The tcl based dealer also has an alternative implementation of losers using the New Losing Trick Count but that is explicitly given the name newLTC - I would suggest that redeal too should do the same

**Comment by anntzer** [comment]
The current LTC implemenation is directly copied from Thomas Andrews's deal implementation (per the source at https://bridge.thomasoandrews.com/deal/downloading.html, implemented in count_losers() in deal.c), and direct compatibility with deal is important to me (or at least, was, back when I implemented this).
I would be rather suspicious of using any Wikipedia article as "standard" reference as I don't think particularly highly of the quality of their bridge material (it's OK, but not what I would call gold standard (The Bridge World, etc.)).

**Comment by palamau** [comment]
I agree with your desire to be compatible with Thomas Andrews' dealer but I was unaware that Thomas Andrews too had implemented the function "losers" this way.  I checked and you are right (except that his function returns "half-losers").

**Comment by palamau** [comment]
Hello ,

I have created a pull request for the redeal code (
https://github.com/anntzer/redeal/pull/41) about a week ago but not
received any response from you.  I hope all is well with you.  Can you
respond to it please?

Thanks

**Comment by anntzer** [comment]
I pushed a new (different) implementation of newltc.  Thanks for the suggestion.
