### ISSUE TITLE
Hand.controls not yet implemented

### ISSUE THREAD

**Issue by palamau** [anntzer/redeal#39]
I see that there is some code to evaluate a hand's controls but the attribute is not yet implemented.  Would it be possible to implement this?

Also note that controls cannot be evaluated using the Evaluator method currently used for hcp since we do not want to count a singleton King as 1 control

**Comment by palamau** [comment]
Actually I think I was wrong about my assertion that a singleton King should not be evaluated as 1 control - I see no reference on the web that suggests this and in any case Thomas Andrews' "deal" already counts it as 1 control so that is a strong reason to count it as 1

**Comment by anntzer** [comment]
Fixed; thanks for pointing that out.
