### ISSUE TITLE
Implement function "parscore" which is a part of Thomas Andrews' "deal"

### ISSUE THREAD

**Issue by palamau** [anntzer/redeal#44]
https://bridge.thomasoandrews.com/deal/commands.html#parscore

**Comment by anntzer** [comment]
Deal's tcl logic (in lib/parscore.tcl) would need to be reimplemented in python; PR welcome.

**Comment by palamau** [comment]
I could try implementing it if you can explain how to test it.  I mean I am not able to figure out how to run the existing examples on my local machine.  I tried creating a local virtual env but am running into errors like this:
(testenv) rvg@rancho:~/git/redeal$ python3 examples/deal2.py 
Traceback (most recent call last):
  File "/home/rvg/git/redeal/examples/deal2.py", line 9, in <module>
    from redeal import *
  File "/home/rvg/git/redeal/redeal/__init__.py", line 7, in <module>
    from .redeal import *
  File "/home/rvg/git/redeal/redeal/redeal.py", line 23, in <module>
    from .parscore import Contract
  File "/home/rvg/git/redeal/redeal/parscore.py", line 1, in <module>
    from .globaldefs import Seat
ModuleNotFoundError: No module named 'redeal.globaldefs'

**Comment by palamau** [comment]
working on it ...

**Comment by palamau** [comment]
Done and submitted a PR

**Comment by palamau** [comment]
Hello Anthony, can you act on the PR please?  Thanks

**Comment by anntzer** [comment]
Done (see PR thread).  Thanks for the initial implementation!

**Comment by palamau** [comment]
The current implementation has a function called par() which is slightly different than the original parscore().  The current implementation returns a list of par contracts whereas the original parscore() returned a single contract returning the par NT contract or the contract with the highest fit.  It will be nice to also implement the original parscore() - an example usecase is one where we want to display a deal and the par contract.  In this scenario it would be preferable that the par contract be in a 9 card fit rather than (say) a 4-2 fit that makes becuase of a very fortunate lie of cards.  Besides it is also more failthful to the orignal implementation

**Comment by anntzer** [comment]
I don't consider being faithful to the original implementation particularly relevant here, especially as I'd consider the criterion (longest fit) somewhat arbitrary.  Fortunately it should be relatively for end users to postprocess the output of par() in whatever way they find desirable.

**Comment by palamau** [comment]
Ok, makes sense though i would have thought it might have been a good idea
for redeal to provide that function out of the box.  Let's close this
discussionon this note 🙂
