### ISSUE TITLE
Playing tricks is different from Richard Pavlicek's table

### ISSUE THREAD

**Issue by phiSgr** [anntzer/redeal#46]
In http://www.rpbridge.net/8j17.htm#4 KT(x) is not listed as a special combination, but instead is listed as Kx worth 0.5 tricks and Kxx worth 1 trick (I don't understand why it's not also 0.5).

https://github.com/anntzer/redeal/blob/4ad479bd12db55c42e10306a16e2ae52696eb658/redeal/redeal.py#L515-L534

Other differences (that I agree with):

- Stiff K is 0 tricks instead of 0.5 tricks
- Qx is 0 tricks instead of 0.5 tricks

BTW the URL fragments are off by 1.

**Comment by anntzer** [comment]
Thanks for noticing that; I agree with the corrections you've made in rektdeal.

I also fixed the URL fragements.
