### ISSUE TITLE
Can't import as submodule without top level __init__.py file

### ISSUE THREAD

**Issue by andrewimcclement** [anntzer/redeal#8]
Hi. First of all, this is a great library.

I'm looking to use redeal in my own github project (https://github.com/andrewimcclement/practice_bidding) and use it as a submodule so if anyone clones it they will automatically get redeal, since it is required for my code.

Current directory structure:
practice_bidding/   (my git repo)
 -  \_\_init\_\_.py
 -  robot_bidding.py
 -  redeal/                (submodule)
    -  redeal.py

and robot_bidding requires redeal.

Messing around with sys.path does not seem ideal to me. If there was an \_\_init\_\_.py under the redeal/ folder, I could just write import redeal.redeal as redeal in robot_bidding.py

My understanding is that since I'm not a collaborator, I can't push to your repo, so I can't make a branch with the \_\_init\_\_.py file and make a pull request, hence why I'm raising it as an issue.

If I am going about this in completely the wrong way, please let me know.

**Comment by anntzer** [comment]
Please use the standard mechanism to install a Python dependency, which is to use pip (https://pip.pypa.io/en/stable/).  As noted in https://github.com/anntzer/redeal#installation, you can do `python -mpip install git+https://github.com/anntzer/redeal` to install redeal.  You can document this, or check whether redeal can be imported and throw an explicit error message asking the user to install redeal (via pip) if not.

Using a toplevel __init__.py is definitely nonstandard.

**Comment by andrewimcclement** [comment]
Thank you for clarifying the best way to go about this.
