### ISSUE TITLE
the problem of command not found

### ISSUE THREAD

**Issue by eleanor11** [anntzer/redeal#9]
Hello,

I'm trying to run this project on my computer. I have followed the installation instruction to install it successfully. However, when I tried to run redeal it responded 'redeal: command not found' under linux and 'redeal is not recognized as an internal or external command' under windows. I wonder if I did something wrong. Please tell me how to run the project properly.

Thank you.

**Comment by anntzer** [comment]
Please indicate what you did to install redeal.

**Comment by eleanor11** [comment]
I have found a solution in another issue that the command ' python -m redeal' works. Sorry to bother you.

**Comment by anntzer** [comment]
no worries.
